# -*- coding: utf-8 -*-
"""area_of_segment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ilFNpKxRFDl1-okK3UWBjP9-6tc1Y0iM

# New Section
"""

r=int(input("radius:"))
from math import pi
x=float(input("angle:"))
area=(pi*r**2)*(x/360)
print("area of segment of a circle:",area)

