# -*- coding: utf-8 -*-
"""character of a string.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ilFNpKxRFDl1-okK3UWBjP9-6tc1Y0iM

# New Section
"""

print("iterate over string using for loop")
for elem in sampleStr:
    print(elem)

