# -*- coding: utf-8 -*-
"""deletion of a character.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ilFNpKxRFDl1-okK3UWBjP9-6tc1Y0iM

# New Section
"""

def remove(string,i):
    for j in range(len(string)):
        if j==i:
            string=string.replace(string[i], " ",1)
    return string
if__name__ == '__main__':
    string="python program"
    i=5
    print(remove(string,i))

