# -*- coding: utf-8 -*-
"""Even or Odd.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ilFNpKxRFDl1-okK3UWBjP9-6tc1Y0iM

# New Section
"""

list1=[21,3,4,6,33,2,3,1,3,76]
even_count,odd_count=0,0
for num in list1:
    if num%2==0:
      even_count+=1
    else:
        odd_count+=1
print("even numbers available in the list:",even_count)
print("odd numbers available in the list:",odd_count)

