# -*- coding: utf-8 -*-
"""Fibonacci_series.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ilFNpKxRFDl1-okK3UWBjP9-6tc1Y0iM

# New Section
"""

n=int(input("Enter the Limit"))
a=0
b=1
count=0
if n<0:
    print("Enter the positive number")
elif n==1:
    print("fibonacci series upto ",n)
    print(a)
else:
    print("fibonacci series are: ")
    while count<n:
        print(a)
        sum=a+b
        a=b
        b=sum
        count=count+1

