# -*- coding: utf-8 -*-
"""H.C.F of the two numbers.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ilFNpKxRFDl1-okK3UWBjP9-6tc1Y0iM

# New Section
"""

def hcf(x,y):
    if x>y:
        smaller=y
    else:
        smaller=y
        for i in range(1,smaller+1):
            if((x%i==0) and (y%i==0)):
                hcf=1
        return hcf
num1=int(input("enter first number:"))
num2=int(input("enter second number:"))
print("the H.C.F. of",num1,"and",num2,"is",hcf(num1,num2))

