# -*- coding: utf-8 -*-
"""length of the string.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ilFNpKxRFDl1-okK3UWBjP9-6tc1Y0iM

# New Section
"""

def findLength(string):
    count=0
    for i in string:
        count+=1
    return count
string="refrigerator"
print(findLength(string))

