# -*- coding: utf-8 -*-
"""list is empty or not.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ilFNpKxRFDl1-okK3UWBjP9-6tc1Y0iM

# New Section
"""

list=[]
num=int(input("how many numbers:"))
for n in range(num):
    numbers=int(input("enter number"))
    list.append(numbers)
print("maximum element in the list is:",max(list))
print("maximun element in the list is:",min(list))

