# -*- coding: utf-8 -*-
"""math_functions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ilFNpKxRFDl1-okK3UWBjP9-6tc1Y0iM

# New Section
"""

import math
print(math.sin(math.pi/3))
print(math.cos(math.pi))
print(math.tan(math.pi/2))
print(math.sin(0.8660254037844386))
print(math.pow(5,8))
print(math.sqrt(400))
print(math.exp(5))
print(math.log2(1024))
print(math.log10(1024))
print(math.floor(23.56),math.ceil(23.56))

