# -*- coding: utf-8 -*-
"""multiple items.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ilFNpKxRFDl1-okK3UWBjP9-6tc1Y0iM

# New Section
"""

def multiply_list(items):
    tot=1
    for x in items:
        tot*=x
        return tot
print(multiply_list([1,2,-8]))

