# -*- coding: utf-8 -*-
"""newline.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ilFNpKxRFDl1-okK3UWBjP9-6tc1Y0iM

# New Section
"""

str1='python exercises\n'
print(str1)
print(str1.rstrip())

