# -*- coding: utf-8 -*-
"""palindrome_or_not.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ilFNpKxRFDl1-okK3UWBjP9-6tc1Y0iM

# New Section
"""

def palindrome():
    try:
        num=int(input("enter a number"))
    except  exception as ValueError:
        print("invalid input enter a integer")
    else:
        temp=num
        rev=0
        while(num>0):
            dig=num%10
            rev=rev*10+dig
            num=num//10
        if(temp==rev):
            print("the number is palindrome")
        else:
            print("not a palindrome")
    finally:
        print("program executed")
palindrome()