# -*- coding: utf-8 -*-
"""prime_or_not.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ilFNpKxRFDl1-okK3UWBjP9-6tc1Y0iM

# New Section
"""

def prime():
    num=int(input("enter any number:"))
    if num>1:
        for i in range(2,num):
            if(num%i==0):
                print(num,"is not a prime number")
                break
            else:
                print(num,"is a prime number")
                break
    else:
        print(num,"is not a prime number")
prime()