# -*- coding: utf-8 -*-
"""random_shuffle.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ilFNpKxRFDl1-okK3UWBjP9-6tc1Y0iM

# New Section
"""

import random
list11=[100,1,2,3,30,40,"hai","hello"]
random.shuffle(list11)
print(list11)

