# -*- coding: utf-8 -*-
"""Range.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ilFNpKxRFDl1-okK3UWBjP9-6tc1Y0iM

# New Section
"""

for x in range(6):
    if(x==3 or x==6):
        continue
    print(x)

