# -*- coding: utf-8 -*-
"""reverse_string.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ilFNpKxRFDl1-okK3UWBjP9-6tc1Y0iM

# New Section
"""

def reverse_string():
    A=str(input("enter the string:"))
    return A[::-1]
reverse_string()