# -*- coding: utf-8 -*-
"""shuffle.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ilFNpKxRFDl1-okK3UWBjP9-6tc1Y0iM

# New Section
"""

from random import shuffle
color=['red','green','white','black','pink','yellow']
shuffle(color)
print(color)

