# -*- coding: utf-8 -*-
"""string in a list.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ilFNpKxRFDl1-okK3UWBjP9-6tc1Y0iM

# New Section
"""

str1="this is ironman"
print(str1.split(' '))
str1="this-is-ironman"
print(str1.split('-'))

