# -*- coding: utf-8 -*-
"""student_marks.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HaUCKBfqzz-SbZC07XCC4FlbW-9TJ9O8
"""

marks=int(input("Enter the marks of the Student"))
if marks >= 35:
  print("Student passed in the exam")
else:
  print("Student failed in the exam")

