# -*- coding: utf-8 -*-
"""sub string in a string.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ilFNpKxRFDl1-okK3UWBjP9-6tc1Y0iM

# New Section
"""

str1 = 'this is Iron man.'
print()
print(str1.count("Iron man"))
print()

