# -*- coding: utf-8 -*-
"""sum_of_squares.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ilFNpKxRFDl1-okK3UWBjP9-6tc1Y0iM

# New Section
"""

def sum_of_squares():
    n=int(input("enter the number"))
    return(n*(n+1)*(2*n+1))/6
sum_of_squares()

