# -*- coding: utf-8 -*-
"""sum_greater_or_equal_or_lesser_than_5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OOvRgLxOUqw0j3fHg8zvTb2ADoP-gMjp
"""

a=int(input("Enter first number"))
    b=int(input("Enter second number"))
    c=a+b
    if c>5:
        print("sum is greater than 5")
    elif c<5:
        print("sum is less than 5")
    else:
        print("sum is equal to 5")