# -*- coding: utf-8 -*-
"""Table of given Number.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ilFNpKxRFDl1-okK3UWBjP9-6tc1Y0iM

# New Section
"""

n=int(input("Enter the number:"))
for i in range(1,11):
    print(n,"x",i,"=",n*i)

