# -*- coding: utf-8 -*-
"""two_strings_equal.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tWdMpgZwyMC_Sbp5iSaa9SRuARW-oXWx
"""

str_1=str(input("Enter the 1st string: "))
    str_2=str(input("Enter the 2nd string: "))
    if str_1==str_2:
        print("both strings are equal")
    else:
        print("both strings are not equal")